### ISSUE TITLE
Updating Mosquitto broker to 6.0.1 stops AM43 from working

### ISSUE THREAD

**Issue by DaveTiff** [buxtronix/am43#28]
Hi, updated my Mosquitto broker from 5.1.1 to 6.0.1 stops AM43 from operating. 

The Blue Tooth Enable works, but the components on HA dashboard remain Greyed Out. Restoring MQTT back to 5.1.1 cures this problem.

Regards, Dave

**Comment by DaveTiff** [comment]
Now not sure it is that, as it has now also stopped working with 5.1.1. Restarting Mosquitto broker allows it to work again.

It has been working fine for over a week, Now running HA 2021.5.5

Anyone else having problems. 

Regards, Dave

**Comment by DaveTiff** [comment]
Another person is now having trouble with Mosquitto broker 6.0.1 and AM43.

https://github.com/buxtronix/am43/issues/27#issuecomment-846403962

**Comment by CaptInsano** [comment]
Also happening here.
HomeAssistant 2021.5.5
Mosquitto: 6.0.1

All other MQTT devices (mainly Tasmota) all still working perfectly

**Comment by Kite-Smurf** [comment]
Hi, The exact same thing happens with my system too:
updated my Mosquitto broker from 5.1.1 to 6.0.1 stops AM43 from operating.

The Blue Tooth Enable works, but the components on HA dashboard remain Greyed Out. Restoring MQTT back to 5.1.1 cures this problem.

Regards,
Otto

**Comment by balbulator** [comment]
added a question in the mosquito thread
https://github.com/home-assistant/addons/issues/2030

**Comment by belenkiy-lab** [comment]
I have several curtains at home.
half are connected via this integration, half are connected via test version in esphome
after updating mqtt those connected via esphome remained working. the rest stopped working like everyone else.

**Comment by balbulator** [comment]
> I have several curtains at home.
> half are connected via this integration, half are connected via test version in esphome
> after updating mqtt those connected via esphome remained working. the rest stopped working like everyone else.

tell me, how exactly did you connect the AM43 to ESPhome in the test?

**Comment by belenkiy-lab** [comment]
It worked for me if I specified "buxtronix: am43" in the Esphome version. After that, everything worked. It was in early March. When I tried to do similar actions in April, I get the same error as yours.
therefore, I started new curtains not through esphome, but through native integration from buxtronix. I decided it was easier than trying to figure it out.
I'm waiting for this integration to be in the esphome release to use it fully and monotonously at home.
-------------------------------------------------------------------
У меня это работало если указать в версии Esphome "buxtronix:am43". После этого все работало. Это было в в начале марта. Когда я пробовал в апреле сделать аналогичные действия, я получаю ошибку, такую же как и у тебя.
поэтому новые шторы я завел не через esphome а через родную интеграцию от buxtronix. Решил что это проще, чем разбираться. 
Жду когда данная интеграция будет в релизе esphome что бы использовать ее полноценно и однообразно у себя.

**Comment by balbulator** [comment]
none of the options work at the moment

**Comment by belenkiy-lab** [comment]
Use mqtt version 5.1.1 and this integration

**Comment by balbulator** [comment]
The problem is that I cannot roll back the mosquitoes

**Comment by belenkiy-lab** [comment]
what prevents you from installing a clean instalation of mosquito not from HA? on any computer on the network or docker?

**Comment by balbulator** [comment]
Everything interferes, on the PC not an option, on the docker, too, as on the Home Assistant

**Comment by belenkiy-lab** [comment]
[https://1drv.ms/u/s!AgyPTdNGxaf8iY1lVEbLF46puzGa2A?e=vV0QSs](url)

this is my mktt snapshot
as I understand you can restore 5.1.1 using it.
will it help?

**Comment by balbulator** [comment]
> [https://1drv.ms/u/s!AgyPTdNGxaf8iY1lVEbLF46puzGa2A?e=vV0QSs](url)
> 
> this is my mqtt snapshot
> as I understand you can restore 5.1.1 using it.
> will it help?

Thanks, I have installed the Mosquitto broker add-on
Current version: 5.1.1, but after HA update (core-2021.6.2) the problem reappeared

**Comment by DaveTiff** [comment]
I am on core-2021.6.2 and Mosquitto broker  5.1.1 mine is still working ok

Re Dave

**Comment by danilkorotkov** [comment]
this is PubSubClient issue, not AM43

**Comment by Kite-Smurf** [comment]
> this is PubSubClient issue, not AM43

Thanks for the updated news on this. The question is how to solve it? and how to get AM43 working with the mqtt 6.0 version?

**Comment by danilkorotkov** [comment]
> Thanks for the updated news on this. The question is how to solve it? and how to get AM43 working with the mqtt 6.0 version?

you can include arduino-mqtt lib instead of PubSubClient  lib and then check all of 22 mqtt methods in your/example sketch)
ota update is available
PubSubClient has no update since 2020 so it is possible that it is abandoned

**Comment by buxtronix** [comment]
I've not got the bad mosquitto version so can't reproduce. Feel free to send a PR and I'll merge a fix that helps.

**Comment by MrBigleg** [comment]
> > Thanks for the updated news on this. The question is how to solve it? and how to get AM43 working with the mqtt 6.0 version?
> 
> you can include arduino-mqtt lib instead of PubSubClient lib and then check all of 22 mqtt methods in your/example sketch)
> ota update is available
> PubSubClient has no update since 2020 so it is possible that it is abandoned

Do you mind sharing your sketch? I tried and just go tonnes of errors compiling

**Comment by CaptInsano** [comment]
Has anyone got a solution for this issue when mosquitto is already at v6.0.1?

I unfortunately have no mosquitto snapshot at earlier version, all other MQTT integrations are still working great but no action from AM43 integration on my system.

Has anyone successfully ported the code to a different MQTT client?

**Comment by timdonovanuk** [comment]
Same issue here. It would help if the serial output had any info or debugging lines about MQTT, as I have no idea whats going on. 

I can see it finding position and battery but nothing is sent to MQTT other than am43/enabled = ON

**Comment by balbulator** [comment]
> Same issue here. It would help if the serial output had any info or debugging lines about MQTT, as I have no idea whats going on.
> 
> I can see it finding position and battery but nothing is sent to MQTT other than am43/enabled = ON

exactly the same with me

**Comment by balbulator** [comment]
https://github.com/buxtronix/am43/issues/21#issuecomment-880215140
Everything can be cured with ESPHome

**Comment by Kite-Smurf** [comment]
> [#21 (comment)](https://github.com/buxtronix/am43/issues/21#issuecomment-880215140)
> Everything can be cured with ESPHome

Could you please share some instructions on how to set this up in ESPHome? I never used that before. Thanks for help.

**Comment by balbulator** [comment]
> > [#21 (comment)](https://github.com/buxtronix/am43/issues/21#issuecomment-880215140)
> > Everything can be cured with ESPHome
> 
> Could you please share some instructions on how to set this up in ESPHome? I never used that before. Thanks for help.

Also important in -> Supervisor -> ESPHome -> Configuration ->
esphome_version - buxtronix:am43
certfile - fullchain.pem
keyfile - privkey.pem


```
esphome:
  name: cover
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "any password"

wifi:
  ssid: "Sergio"
  password: "Password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cover Fallback Hotspot"
    password: "StW7wyE8nD6N"

captive_portal:

esp32_ble_tracker:

ble_client:
  - mac_address: 01:02:03:AA:BB:CC
    id: blinds

cover:
  - platform: am43
    name: "Blinds in bedroom"
    id: cover_bedroom
    ble_client_id: blinds

sensor:
  - platform: am43
    ble_client_id: blinds
    battery_level:
      name: "Blinds battery"
    illuminance:
      name: "Blinds light"
    update_interval: 120s
  - platform: uptime
    name: Uptime Sensor


switch:
  - platform: restart
    name: "Device Restart"
  - platform: ble_client
    name: "Blinds  On"
    ble_client_id: cover
    id: right_on

```
